"""add scoring_config table and account sentiment fields

Revision ID: 1cd98b3d21f4
Revises: d434e885e84c
Create Date: 2026-05-11 16:00:45.456879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd98b3d21f4'
down_revision: Union[str, Sequence[str], None] = 'd434e885e84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_name')
    )
    op.add_column('accounts', sa.Column('ticket_trend', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('csm_sentiment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'csm_sentiment')
    op.drop_column('accounts', 'ticket_trend')
    op.drop_table('scoring_config')
    # ### end Alembic commands ###
